//! Safe encoding of Redis configuration values.
//!
//! Redis parses each config line with `sdssplitargs`, the same splitter
//! redis-cli uses for interactive input. It splits on unquoted whitespace,
//! honours double- and single-quoted tokens, treats a `#` that begins a token
//! as a comment, and ends the directive at a newline.
//!
//! Interpolating a value directly into a config line therefore lets the value
//! change the meaning of the line. A password containing a space becomes two
//! arguments, one containing `#` is truncated to a comment, and one containing
//! a newline appends an entirely new directive.
//!
//! [`encode`] renders a value as exactly one token that `sdssplitargs` reads
//! back verbatim.

/// Encode a value as a single Redis configuration token.
///
/// Values made up entirely of characters that `sdssplitargs` treats as
/// ordinary are returned unchanged, so generated configs stay readable. Every
/// other value is wrapped in double quotes, with `"` and `\` backslash-escaped
/// and control characters written as the escapes Redis understands.
///
/// The empty string always encodes to `""`, since emitting nothing would drop
/// the argument entirely.
///
/// # Example
///
/// ```
/// use redis_server_wrapper::config_token::encode;
///
/// assert_eq!(encode("simple"), "simple");
/// assert_eq!(encode("two words"), "\"two words\"");
/// assert_eq!(encode("has\"quote"), "\"has\\\"quote\"");
/// assert_eq!(encode(""), "\"\"");
/// ```
pub fn encode(value: &str) -> String {
    if !value.is_empty() && value.chars().all(is_bare_safe) {
        return value.to_string();
    }

    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\x08' => out.push_str("\\b"),
            '\x0b' => out.push_str("\\x0b"),
            '\x0c' => out.push_str("\\f"),
            '\x07' => out.push_str("\\a"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                out.push_str(&format!("\\x{:02x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Encode a directive and its arguments as a complete config line, including
/// the trailing newline.
///
/// The key is emitted verbatim: keys come from the crate, never from caller
/// input, and quoting them would break Redis parsing. Every argument is passed
/// through [`encode`].
///
/// # Example
///
/// ```
/// use redis_server_wrapper::config_token::directive;
///
/// assert_eq!(directive("requirepass", ["pw with space"]), "requirepass \"pw with space\"\n");
/// ```
pub fn directive<I, S>(key: &str, args: I) -> String
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut line = String::from(key);
    for arg in args {
        line.push(' ');
        line.push_str(&encode(arg.as_ref()));
    }
    line.push('\n');
    line
}

/// Config directives the wrapper generates and depends on.
///
/// The wrapper keeps its own copy of these values and uses them after startup
/// for readiness probing, command routing, and teardown. Letting a caller set
/// them through an escape hatch such as `extra()` would let the running server
/// and the handle disagree: `extra("port", "6380")` produces a server the
/// handle can neither probe nor stop.
const RESERVED_DIRECTIVES: &[&str] = &[
    // lifecycle
    "port",
    "bind",
    "daemonize",
    "pidfile",
    "dir",
    "logfile",
    "unixsocket",
    "unixsocketperm",
    // auth
    "requirepass",
    "masterauth",
    "masteruser",
    "aclfile",
    // transport
    "tls-port",
    "tls-cert-file",
    "tls-key-file",
    "tls-ca-cert-file",
    "tls-ca-cert-dir",
    "tls-auth-clients",
    "tls-replication",
    "tls-cluster",
    // replication
    "replicaof",
    "slaveof",
    // cluster
    "cluster-enabled",
    "cluster-config-file",
    "cluster-node-timeout",
    // modules
    "loadmodule",
];

/// Whether a directive is generated by the wrapper and cannot be overridden.
///
/// Comparison is case-insensitive: Redis directive names are not
/// case-sensitive, so `PORT` must be rejected alongside `port`.
///
/// # Example
///
/// ```
/// use redis_server_wrapper::config_token::is_reserved;
///
/// assert!(is_reserved("port"));
/// assert!(is_reserved("LoadModule"));
/// assert!(!is_reserved("maxmemory"));
/// ```
pub fn is_reserved(key: &str) -> bool {
    RESERVED_DIRECTIVES
        .iter()
        .any(|d| d.eq_ignore_ascii_case(key.trim()))
}

/// Characters that survive `sdssplitargs` outside of quotes.
///
/// Deliberately conservative: anything outside this set gets quoted rather
/// than reasoned about. `#` is excluded because it starts a comment, and all
/// non-ASCII is excluded because a config file's encoding is not guaranteed.
fn is_bare_safe(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '/' | ':' | '+' | '=' | '@' | ',')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_values_stay_bare() {
        assert_eq!(encode("notice"), "notice");
        assert_eq!(encode("/var/lib/redis/mod.so"), "/var/lib/redis/mod.so");
        assert_eq!(encode("127.0.0.1:6379"), "127.0.0.1:6379");
        assert_eq!(encode("100mb"), "100mb");
    }

    #[test]
    fn empty_value_becomes_empty_quotes() {
        assert_eq!(encode(""), "\"\"");
    }

    #[test]
    fn whitespace_is_quoted() {
        assert_eq!(encode("two words"), "\"two words\"");
        assert_eq!(encode(" leading"), "\" leading\"");
        assert_eq!(encode("trailing "), "\"trailing \"");
    }

    #[test]
    fn quotes_and_backslashes_are_escaped() {
        assert_eq!(encode("has\"quote"), "\"has\\\"quote\"");
        assert_eq!(encode("has\\slash"), "\"has\\\\slash\"");
        assert_eq!(encode("both\"and\\"), "\"both\\\"and\\\\\"");
    }

    #[test]
    fn comment_marker_is_quoted() {
        assert_eq!(encode("hunter2 # notes"), "\"hunter2 # notes\"");
        assert_eq!(encode("#leading"), "\"#leading\"");
    }

    #[test]
    fn newlines_cannot_inject_a_directive() {
        let encoded = encode("pw\nrequirepass other");
        assert_eq!(encoded, "\"pw\\nrequirepass other\"");
        assert!(!encoded.contains('\n'));
    }

    #[test]
    fn control_characters_are_escaped() {
        assert_eq!(encode("a\tb"), "\"a\\tb\"");
        assert_eq!(encode("a\rb"), "\"a\\rb\"");
        assert_eq!(encode("a\x01b"), "\"a\\x01b\"");
        assert_eq!(encode("a\x7fb"), "\"a\\x7fb\"");
    }

    #[test]
    fn single_quotes_are_quoted_but_not_escaped() {
        // Inside a double-quoted token a single quote is an ordinary
        // character, but a bare token starting with one would open a
        // single-quoted token, so the value must still be wrapped.
        assert_eq!(encode("it's"), "\"it's\"");
    }

    #[test]
    fn non_ascii_is_quoted() {
        assert_eq!(encode("café"), "\"café\"");
    }

    #[test]
    fn directive_renders_a_full_line() {
        assert_eq!(directive("save", ["900", "1"]), "save 900 1\n");
        assert_eq!(
            directive("loadmodule", ["/x/mod.so", "--prefix", "my events"]),
            "loadmodule /x/mod.so --prefix \"my events\"\n"
        );
        assert_eq!(directive("appendonly", ["yes"]), "appendonly yes\n");
    }

    #[test]
    fn directive_with_no_args_is_just_the_key() {
        assert_eq!(directive("save", Vec::<String>::new()), "save\n");
    }
}
